name: Build LKM for KernelSU
on:
  workflow_call:
    inputs:
      manager_package:
        description: 'manager package name'
        required: false
        default: ''
        type: string
      expected_manager_size:
        description: 'expected signature size'
        required: false
        default: ''
        type: string
      expected_manager_hash:
        description: 'expected signature hash'
        required: false
        default: ''
        type: string
  workflow_dispatch:
jobs:
  build-lkm:
    strategy:
      matrix:
        kmi:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12
          - android17-6.18
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: ${{ matrix.kmi }}
      manager_package: ${{ inputs.manager_package || '' }}
      expected_manager_size: ${{ inputs.expected_manager_size || '' }}
      expected_manager_hash: ${{ inputs.expected_manager_hash || '' }}
